"use client"

import React, { createContext, useContext, useState, useEffect, useCallback } from "react"
import { useAuth } from "@/components/auth-context"
import * as SupabaseProfileStorage from "@/lib/supabase-profile-storage"
import { getCurrentProfile, setCurrentProfile as setCurrentProfileStorage } from "@/lib/supabase-profile-storage"

interface ProfileData {
  id: string
  name: string
  age: number
  weight: number
  height: number
  gender: "male" | "female"
  activityLevel: string
  dietaryPreference: string
  goal: string
  avatar?: string
  createdAt: string
}

interface ProfileContextType {
  currentProfile: ProfileData | null
  profiles: ProfileData[]
  updateCurrentProfile: (profile: ProfileData) => void
  updateProfiles: (profiles: ProfileData[]) => void
  switchProfile: (profile: ProfileData) => void
  setActiveTab: (tab: string) => void
  activeTab: string
  profileAvatar: string | null
  setProfileAvatar: (avatar: string | null) => void
  createProfile: (profile: Omit<ProfileData, 'id' | 'createdAt'>) => Promise<ProfileData | null>
  deleteProfile: (profileId: string) => Promise<boolean>
  loading: boolean
}

const ProfileContext = createContext<ProfileContextType | null>(null)

export function useProfileContext() {
  const ctx = useContext(ProfileContext)
  if (!ctx) throw new Error("useProfileContext must be used within ProfileProvider")
  return ctx
}

export function ProfileProvider({ children }: { children: React.ReactNode }) {
  const { user } = useAuth()
  const [currentProfile, setCurrentProfileState] = useState<ProfileData | null>(null)
  const [profiles, setProfiles] = useState<ProfileData[]>([])
  const [activeTab, setActiveTab] = useState("dashboard")
  const [profileAvatar, setProfileAvatar] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const loadProfiles = async () => {
      if (!user) {
        setProfiles([])
        setCurrentProfileState(null)
        setLoading(false)
        return
      }

      try {
        setLoading(true)
        const userProfiles = await SupabaseProfileStorage.getUserProfiles(user.id)
        setProfiles(userProfiles)

        // Try to get current profile from localStorage
        const savedCurrentProfile = getCurrentProfile()
        
        if (savedCurrentProfile && userProfiles.find(p => p.id === savedCurrentProfile.id)) {
          setCurrentProfileState(savedCurrentProfile)
        } else if (userProfiles.length > 0) {
          // Default to first profile if no valid saved profile
          setCurrentProfileState(userProfiles[0])
          setCurrentProfileStorage(userProfiles[0])
        } else {
          setCurrentProfileState(null)
        }
      } catch (error) {
        console.error('Error loading profiles:', error)
      } finally {
        setLoading(false)
      }
    }

    loadProfiles()
  }, [user])

  const updateCurrentProfile = useCallback(async (profile: ProfileData) => {
    try {
      const updatedProfile = await SupabaseProfileStorage.updateProfile(profile)
      if (updatedProfile) {
        setCurrentProfileState(updatedProfile)
        setCurrentProfileStorage(updatedProfile)
        
        // Update in profiles list
        setProfiles(prev => {
          const updated = prev.map(p => p.id === profile.id ? updatedProfile : p)
          return updated
        })
      }
    } catch (error) {
      console.error('Error updating profile:', error)
    }
  }, [])

  const updateProfiles = useCallback((newProfiles: ProfileData[]) => {
    setProfiles(newProfiles)
  }, [])

  const switchProfile = useCallback((profile: ProfileData) => {
    setCurrentProfileState(profile)
    setCurrentProfileStorage(profile)
  }, [])

  const createProfile = useCallback(async (profileData: Omit<ProfileData, 'id' | 'createdAt'>): Promise<ProfileData | null> => {
    if (!user) return null

    try {
      const newProfile = await SupabaseProfileStorage.createProfile({
        ...profileData,
        id: '', // Will be generated by Supabase
        createdAt: new Date().toISOString()
      }, user.id)

      if (newProfile) {
        setProfiles(prev => [...prev, newProfile])
        // If this is the first profile, set it as current
        if (profiles.length === 0) {
          setCurrentProfileState(newProfile)
          setCurrentProfileStorage(newProfile)
        }
      }

      return newProfile
    } catch (error) {
      console.error('Error creating profile:', error)
      return null
    }
  }, [user, profiles.length])

  const deleteProfile = useCallback(async (profileId: string): Promise<boolean> => {
    if (!user) return false

    try {
      const success = await SupabaseProfileStorage.deleteProfile(profileId)
      if (success) {
        setProfiles(prev => prev.filter(p => p.id !== profileId))
        
        // If deleted profile was current, switch to another one
        if (currentProfile?.id === profileId) {
          const remainingProfiles = profiles.filter(p => p.id !== profileId)
          if (remainingProfiles.length > 0) {
            const newCurrent = remainingProfiles[0]
            setCurrentProfileState(newCurrent)
            setCurrentProfileStorage(newCurrent)
          } else {
            setCurrentProfileState(null)
          }
        }
      }
      return success
    } catch (error) {
      console.error('Error deleting profile:', error)
      return false
    }
  }, [user, currentProfile, profiles])

  const handleSetProfileAvatar = useCallback((avatar: string | null) => {
    setProfileAvatar(avatar)
    if (avatar) {
      localStorage.setItem("nutritrack-avatar", avatar)
    } else {
      localStorage.removeItem("nutritrack-avatar")
    }
  }, [])

  return (
    <ProfileContext.Provider
      value={{
        currentProfile,
        profiles,
        updateCurrentProfile,
        updateProfiles,
        switchProfile,
        setActiveTab,
        activeTab,
        profileAvatar,
        setProfileAvatar: handleSetProfileAvatar,
        createProfile,
        deleteProfile,
        loading
      }}
    >
      {children}
    </ProfileContext.Provider>
  )
}
